[phases.setup]
nixPkgs = ["nodejs-22_x"]

[phases.install]
cmds = ["npm i --ignore-scripts", "cd server && npm i", "cd client && npm i"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "npm run db:migrate && cd server && node index.js"
